site_name: CRMSync
site_url: https://mabecenter-it.github.io/crmsync
repo_url: https://github.com/mabecenter-it/crmsync
repo_name: mabecenter-it/crmsync

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - Syncer:
      - crmsync/syncer/syncer.md
      - crmsync/syncer/assembler/policy_assembler.md
      - crmsync/syncer/assembler/core/pipeline.md
      - crmsync/syncer/assembler/core/step.md
      - crmsync/syncer/assembler/factories/base.md
      - crmsync/syncer/assembler/factories/address.md
      - crmsync/syncer/assembler/factories/bank_account.md
      - crmsync/syncer/assembler/factories/contact.md
      - crmsync/syncer/assembler/factories/customer.md
      - crmsync/syncer/assembler/factories/item.md
      - crmsync/syncer/assembler/factories/salesorder.md
      - crmsync/syncer/assembler/handlers/address.md
      - crmsync/syncer/assembler/handlers/bank_account.md
      - crmsync/syncer/assembler/handlers/base.md
      - crmsync/syncer/assembler/handlers/contact.md
      - crmsync/syncer/assembler/handlers/customer.md
      - crmsync/syncer/assembler/handlers/item.md
      - crmsync/syncer/assembler/handlers/salesorder.md
      - crmsync/syncer/assembler/linkers/address.md
      - crmsync/syncer/assembler/linkers/base.md
      - crmsync/syncer/assembler/linkers/contact.md
      - crmsync/syncer/assembler/linkers/document.md
      - crmsync/syncer/assembler/resolvers/simple_name.md
      - crmsync/syncer/utils/comparator.md
      - crmsync/syncer/utils/entry_parser_doc_simple.md
      - crmsync/syncer/utils/entry_parser_doc.md
      - crmsync/syncer/utils/entry_parser_issue.md
  - Database:
      - crmsync/database/base.md
      - crmsync/database/engine.md
      - crmsync/database/unit_of_work.md
      - crmsync/database/models/vtigercrm_contactcf.md
      - crmsync/database/models/vtigercrm_contactdetails.md
      - crmsync/database/models/vtigercrm_crmentity.md
      - crmsync/database/models/vtigercrm_salesorder.md
      - crmsync/database/models/vtigercrm_salesordercf.md
      - crmsync/database/models/vtigercrm_ticketcf.md
      - crmsync/database/models/vtigercrm_troubletickets.md
      - crmsync/database/services/query.md

theme:
  name: material
  language: en

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      baselevel: 2
